/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','郭为民','总监/资深经理','信息化管理','13910783717','wmguoboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','奚舸','经理 (有下属员工)','IT部门','13681397929','gexiboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','董炎','员工','IT部门','13991160360','yandongboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','晏云桥','员工','IT部门','18605650239','yqyanboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','陈晓燕','经理 (无下属员工)','IT部门','13651291015','xychenboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','张思宇','经理 (无下属员工)','IT部门','13701373201','syzhangboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','薛伟','经理 (有下属员工)','IT部门','13910765743','weixueboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','贾国政','经理 (无下属员工)','研究 / 开发','13910329103','gzjiaboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','兰萍','经理 (有下属员工)','研究 / 开发','13923736361','pinhlanboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,mobile,email,province,city,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,cc)values ('中国银行','客户','史伟杰','经理 (有下属员工)','IT部门','13910021432','wjshiboc@gmail.com','beijing','beijing','Peng Yuan','yuapeng','18601362027','CL-Headquarter','Zhang Yu','yuzhan3','Jerry Fan','jifan','CL','1','yuapeng@cisco.com');
