insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-Norman  ','OD','','','','','Norman  ','','','','','','','','','','','','','','12','200');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-wub  ','OD','','','','','wub  ','','','','','','','','','','','','','','12','201');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-loutong  ','OD','','','','','loutong  ','','','','','','','','','','','','','','12','202');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-pshao  ','OD','','','','','pshao  ','','','','','','','','','','','','','','12','203');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-guahai  ','OD','','','','','guahai  ','','','','','','','','','','','','','','12','204');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-jerzhang  ','OD','','','','','jerzhang  ','','','','','','','','','','','','','','12','205');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-norlam  ','OD','','','','','norlam  ','','','','','','','','','','','','','','12','206');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-raymondw  ','OD','','','','','raymondw  ','','','','','','','','','','','','','','12','207');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-jfan  ','OD','','','','','jfan  ','','','','','','','','','','','','','','12','208');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-noalam  ','OD','','','','','noalam  ','','','','','','','','','','','','','','12','209');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-jifan  ','OD','','','','','jifan  ','','','','','','','','','','','','','','12','210');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-pauwheel  ','OD','','','','','pauwheel  ','','','','','','','','','','','','','','12','211');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-tchsi  ','OD','','','','','tchsi  ','','','','','','','','','','','','','','12','212');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-kqi  ','OD','','','','','kqi  ','','','','','','','','','','','','','','12','213');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-jehuang  ','OD','','','','','jehuang  ','','','','','','','','','','','','','','12','214');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-mbischof  ','OD','','','','','mbischof  ','','','','','','','','','','','','','','12','215');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-jiahzhan  ','OD','','','','','jiahzhan  ','','','','','','','','','','','','','','12','216');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','OD-lizhang  ','OD','','','','','lizhang  ','','','','','','','','','','','','','','12','217');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-qiaogang  ','RM','','','','','qiaogang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-qiur  ','RM','','','','','qiur  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-binche  ','RM','','','','','binche  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-arsun  ','RM','','','','','arsun  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-liufrank  ','RM','','','','','liufrank  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-wmchen  ','RM','','','','','wmchen  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-fzhu  ','RM','','','','','fzhu  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-bzhuo  ','RM','','','','','bzhuo  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-kbzheng  ','RM','','','','','kbzheng  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-vichang  ','RM','','','','','vichang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-qiaogang  ','RM','','','','','qiaogang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-chaijian  ','RM','','','','','chaijian  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-bizhou  ','RM','','','','','bizhou  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-raymondw  ','RM','','','','','raymondw  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-shishen  ','RM','','','','','shishen  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-yongye  ','RM','','','','','yongye  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-huilyuan  ','RM','','','','','huilyuan  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-pauwheel  ','RM','','','','','pauwheel  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-qimi  ','RM','','','','','qimi  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-junhe  ','RM','','','','','junhe  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-cbsun  ','RM','','','','','cbsun  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-aileenzh  ','RM','','','','','aileenzh  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-liuqun  ','RM','','','','','liuqun  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-qingxu  ','RM','','','','','qingxu  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-seanjian  ','RM','','','','','seanjian  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-yuzhan3  ','RM','','','','','yuzhan3  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-riliu  ','RM','','','','','riliu  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-luhua  ','RM','','','','','luhua  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-jdli  ','RM','','','','','jdli  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-xwu  ','RM','','','','','xwu  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-gujiang  ','RM','','','','','gujiang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-jzheng  ','RM','','','','','jzheng  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-lijd  ','RM','','','','','lijd  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-honchen  ','RM','','','','','honchen  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-yye  ','RM','','','','','yye  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-joeplin  ','RM','','','','','joeplin  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-xuren  ','RM','','','','','xuren  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-haizzhu  ','RM','','','','','haizzhu  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-kbzhen  ','RM','','','','','kbzhen  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-jehuang  ','RM','','','','','jehuang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-kepan  ','RM','','','','','kepan  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-spxia  ','RM','','','','','spxia  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-xinzhang  ','RM','','','','','xinzhang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-miluo  ','RM','','','','','miluo  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-lizhang  ','RM','','','','','lizhang  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','RM-dtse  ','RM','','','','','dtse  ','','','','','','','','','','','','','','11','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-alvinzh  ','AM','','','','','alvinzh  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang10  ','AM','','','','','artwang10  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang11  ','AM','','','','','artwang11  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang12  ','AM','','','','','artwang12  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang13  ','AM','','','','','artwang13  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang15  ','AM','','','','','artwang15  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang16  ','AM','','','','','artwang16  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang17  ','AM','','','','','artwang17  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang18  ','AM','','','','','artwang18  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang19  ','AM','','','','','artwang19  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang2  ','AM','','','','','artwang2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang20  ','AM','','','','','artwang20  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang21  ','AM','','','','','artwang21  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang22  ','AM','','','','','artwang22  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang23  ','AM','','','','','artwang23  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang24  ','AM','','','','','artwang24  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang25  ','AM','','','','','artwang25  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang26  ','AM','','','','','artwang26  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang27  ','AM','','','','','artwang27  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang28  ','AM','','','','','artwang28  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang29  ','AM','','','','','artwang29  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang3  ','AM','','','','','artwang3  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang30  ','AM','','','','','artwang30  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang31  ','AM','','','','','artwang31  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang32  ','AM','','','','','artwang32  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang33  ','AM','','','','','artwang33  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang4  ','AM','','','','','artwang4  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang5  ','AM','','','','','artwang5  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang6  ','AM','','','','','artwang6  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang7  ','AM','','','','','artwang7  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang8  ','AM','','','','','artwang8  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-artwang9  ','AM','','','','','artwang9  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-benyi  ','AM','','','','','benyi  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-biljiang  ','AM','','','','','biljiang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-binli3  ','AM','','','','','binli3  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-binya  ','AM','','','','','binya  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-bobbyli  ','AM','','','','','bobbyli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-bowang2  ','AM','','','','','bowang2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-chaosun  ','AM','','','','','chaosun  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-chawang  ','AM','','','','','chawang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-chenggs  ','AM','','','','','chenggs  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-cholong  ','AM','','','','','cholong  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-chyuan  ','AM','','','','','chyuan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-chzheng  ','AM','','','','','chzheng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-dizhang  ','AM','','','','','dizhang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-docai  ','AM','','','','','docai  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-gangjin  ','AM','','','','','gangjin  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-garen  ','AM','','','','','garen  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-garge  ','AM','','','','','garge  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-garyli  ','AM','','','','','garyli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-glennwu  ','AM','','','','','glennwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-haigu  ','AM','','','','','haigu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-haiyliu  ','AM','','','','','haiyliu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-haoli  ','AM','','','','','haoli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-haowan  ','AM','','','','','haowan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-huanwan  ','AM','','','','','huanwan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jackyche  ','AM','','','','','jackyche  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jashe  ','AM','','','','','jashe  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jerrycha  ','AM','','','','','jerrycha  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jialiu  ','AM','','','','','jialiu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jianxyan  ','AM','','','','','jianxyan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiawan2  ','AM','','','','','jiawan2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiaxiao  ','AM','','','','','jiaxiao  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiayan  ','AM','','','','','jiayan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jieya2  ','AM','','','','','jieya2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jieyong  ','AM','','','','','jieyong  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiezpeng  ','AM','','','','','jiezpeng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jingjia  ','AM','','','','','jingjia  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jingjliu  ','AM','','','','','jingjliu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiqian  ','AM','','','','','jiqian  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiwa  ','AM','','','','','jiwa  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiwang2  ','AM','','','','','jiwang2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jufeng  ','AM','','','','','jufeng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-juliewa  ','AM','','','','','juliewa  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-junge  ','AM','','','','','junge  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-junhwang  ','AM','','','','','junhwang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-juyli  ','AM','','','','','juyli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-kaihe  ','AM','','','','','kaihe  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-kejwu  ','AM','','','','','kejwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-kgao  ','AM','','','','','kgao  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-kunwu  ','AM','','','','','kunwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-kunzha  ','AM','','','','','kunzha  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lakliang  ','AM','','','','','lakliang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lechen2  ','AM','','','','','lechen2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lehuan  ','AM','','','','','lehuan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-liangw  ','AM','','','','','liangw  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lianwang  ','AM','','','','','lianwang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lijian2  ','AM','','','','','lijian2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lijie  ','AM','','','','','lijie  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lilidong  ','AM','','','','','lilidong  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-linaw  ','AM','','','','','linaw  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-LIPEN  ','AM','','','','','LIPEN  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-liuyan  ','AM','','','','','liuyan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lixie  ','AM','','','','','lixie  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lizang  ','AM','','','','','lizang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lucyguo  ','AM','','','','','lucyguo  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-mdecheng  ','AM','','','','','mdecheng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-mehan  ','AM','','','','','mehan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-mingszha  ','AM','','','','','mingszha  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-mingzha2  ','AM','','','','','mingzha2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-mingzhao  ','AM','','','','','mingzhao  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-minyan  ','AM','','','','','minyan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-nshang  ','AM','','','','','nshang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-nzhan  ','AM','','','','','nzhan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-paliu2  ','AM','','','','','paliu2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-payu  ','AM','','','','','payu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-peihuang  ','AM','','','','','peihuang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-peterwei  ','AM','','','','','peterwei  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-pezhou  ','AM','','','','','pezhou  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-pingwa  ','AM','','','','','pingwa  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-qiafu  ','AM','','','','','qiafu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-qijiang  ','AM','','','','','qijiang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-qiur  ','AM','','','','','qiur  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-quyuan  ','AM','','','','','quyuan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-rushen  ','AM','','','','','rushen  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-ruwei  ','AM','','','','','ruwei  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-shaqiu  ','AM','','','','','shaqiu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-shcao  ','AM','','','','','shcao  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-shengwu  ','AM','','','','','shengwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-shuoli  ','AM','','','','','shuoli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-sizhang  ','AM','','','','','sizhang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-squandao  ','AM','','','','','squandao  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-stliu  ','AM','','','','','stliu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-taoli  ','AM','','','','','taoli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-tiali  ','AM','','','','','tiali  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-tianyang  ','AM','','','','','tianyang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-trfeng  ','AM','','','','','trfeng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wangeric  ','AM','','','','','wangeric  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wanglin  ','AM','','','','','wanglin  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wangrui  ','AM','','','','','wangrui  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wangye  ','AM','','','','','wangye  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wdu  ','AM','','','','','wdu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wedu  ','AM','','','','','wedu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wefeng  ','AM','','','','','wefeng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-weixiche  ','AM','','','','','weixiche  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wenbwu  ','AM','','','','','wenbwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wenhhuan  ','AM','','','','','wenhhuan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-wzhang3  ','AM','','','','','wzhang3  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xiaan  ','AM','','','','','xiaan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xiaoqin  ','AM','','','','','xiaoqin  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xiaoxzha  ','AM','','','','','xiaoxzha  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xiaoyliu  ','AM','','','','','xiaoyliu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xiaozhou  ','AM','','','','','xiaozhou  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xikang  ','AM','','','','','xikang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xingoli  ','AM','','','','','xingoli  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xipang  ','AM','','','','','xipang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-XMU  ','AM','','','','','XMU  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xurhuang  ','AM','','','','','xurhuang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xutjiang  ','AM','','','','','xutjiang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yanchi  ','AM','','','','','yanchi  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yangche3  ','AM','','','','','yangche3  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yanqyu  ','AM','','','','','yanqyu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yanshi  ','AM','','','','','yanshi  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-ybgao  ','AM','','','','','ybgao  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yehuang  ','AM','','','','','yehuang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yingche  ','AM','','','','','yingche  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yingche2  ','AM','','','','','yingche2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yipwu  ','AM','','','','','yipwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yix2  ','AM','','','','','yix2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-ykejian  ','AM','','','','','ykejian  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yonzhang  ','AM','','','','','yonzhang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-Yoxue  ','AM','','','','','Yoxue  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yuesun  ','AM','','','','','yuesun  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yye  ','AM','','','','','yye  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zexin  ','AM','','','','','zexin  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zgeng  ','AM','','','','','zgeng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhangjia  ','AM','','','','','zhangjia  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhew  ','AM','','','','','zhew  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhihwang  ','AM','','','','','zhihwang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhmei  ','AM','','','','','zhmei  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhouqwan  ','AM','','','','','zhouqwan  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhupwang  ','AM','','','','','zhupwang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zzhonghu  ','AM','','','','','zzhonghu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-hanjiang  ','AM','','','','','hanjiang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xuren  ','AM','','','','','xuren  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-haizzhu  ','AM','','','','','haizzhu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-liuju  ','AM','','','','','liuju  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xingkata  ','AM','','','','','xingkata  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jane  ','AM','','','','','jane  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-aweng  ','AM','','','','','aweng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-yuapeng  ','AM','','','','','yuapeng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-haxie  ','AM','','','','','haxie  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xuya2  ','AM','','','','','xuya2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xuefwu  ','AM','','','','','xuefwu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jiantian  ','AM','','','','','jiantian  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-aibliu  ','AM','','','','','aibliu  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-hongshen  ','AM','','','','','hongshen  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-jigzhang  ','AM','','','','','jigzhang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lli2  ','AM','','','','','lli2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-xichen2  ','AM','','','','','xichen2  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-zhacheng  ','AM','','','','','zhacheng  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-lizhang  ','AM','','','','','lizhang  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-hedsong  ','AM','','','','','hedsong  ','','','','','','','','','','','','','','10','');
insert into users (organisation,relation_with_cisco,full_name,job_title,department,working_phone_dis,working_phone,mobile,email,province,city,id,password,am_name,am_id,am_mobile,am_department,rm_name,rm_id,od_name,od_id,diff,type_id,ec_mobile)
values ('','','AM-qiwen  ','AM','','','','','qiwen  ','','','','','','','','','','','','','','10','');